### ISSUE TITLE
跳了大约10分钟左右，最高分是108，请问可以提供训练模型的代码玩一玩吗

### ISSUE THREAD

**Issue by yaochao** [songrotek/wechat_jump_end_to_end#2]
先谢谢repo主的分享

**Comment by floodsung** [comment]
你好！训练代码在另一个git https://github.com/songrotek/wechat_jump_end_to_end_train
你可以调整一下scale值，几千分没有问题的。
目前这个模型不是特别好。比用vgg的差。但是vgg的太大了不好上传。

**Comment by zkailinzhang** [comment]
博主大神，你好，vgg的能否提供个百度云链接，想好好学习下
