### ISSUE TITLE
一直小碎步在同一个方块往前跳……

### ISSUE THREAD

**Issue by haganenokokoro** [songrotek/wechat_jump_end_to_end#5]
0分就挂了……调调节scale也没用，iphone 8p…

**Comment by haganenokokoro** [comment]
可能出现问题的地方。1. 直接用wda.client()t，没填ip，因为之前的传统版本也是这样 2.在Jupyter notebook上跑的代码……
但理论上既然跑起来了，上面两个应该都不算问题吧……小白一个，求大神指点……

**Comment by floodsung** [comment]
手机连接上有问题吗？按道理不调scale也直接能跑出一定分数的

**Comment by floodsung** [comment]
能截屏看一下吗

**Comment by haganenokokoro** [comment]
<img width="274" alt="2018-01-12 11 10 01" src="https://user-images.githubusercontent.com/23055312/34858229-047cbc70-f78a-11e7-9519-c81dabe53957.png">
<img width="159" alt="2018-01-12 11 11 11" src="https://user-images.githubusercontent.com/23055312/34858231-06655c72-f78a-11e7-930b-33a47f7fc671.png">

**Comment by floodsung** [comment]
是不是没有load model

**Comment by haganenokokoro** [comment]
第一张图是我唯一修改了代码的地方，第二张图是跳了两次后相应的输出，我是在jupyter notebook上跑的。。手机连接应该没问题，因为毕竟已经在跳了，只不过是跳的幅度太小

**Comment by haganenokokoro** [comment]
哦哦这个原代码里面没有是吗

**Comment by floodsung** [comment]
if os.path.exists("./model.pkl"):
        net.load_state_dict(torch.load("./model.pkl",map_location=lambda storage, loc: storage))
        print("load model")

**Comment by floodsung** [comment]
你如果没有显示load model说明没有load进去

**Comment by haganenokokoro** [comment]
原来如此！那是不是说明我pytorch没装好。。还是其他什么原因呢？

**Comment by floodsung** [comment]
我不知道是不是你在jupyter跑没有找到路径。你要不在terminal下面跑一下看看

**Comment by haganenokokoro** [comment]
嗯嗯谢谢！我试试

**Comment by haganenokokoro** [comment]
解决了，果然是这个文件路径的问题！谢谢！正在跳，不知道神经网络版本会不会被腾讯反作弊给挂掉哈哈

**Comment by floodsung** [comment]
现在1000以上就不行了。你可以增加一些随机的延时等等操作

**Comment by haganenokokoro** [comment]
嗯嗯谢谢，不过我1000以上居然没被ban掉哈哈

**Comment by floodsung** [comment]
不，你只是自己看到了，别人不一定能看到

**Comment by haganenokokoro** [comment]
我验证过啦，一般微信后台关掉再重启还能看到说明就没被ban掉哈哈，这回我让朋友也验过了，确实在。。腾讯的反作弊系统还是很诡异的。。

**Comment by floodsung** [comment]
那不错啊！👍
